const puppeteer = require('puppeteer');
const request = require('request');

puppeteer.launch({headless: false}).then(async browser => {
    try{
        var i = 0;
        var page = await browser.newPage();
        universalPage = page;
        console.log('Filling out your Toaster Timesheet...');
        await page.goto('https://www.myu.umn.edu/psp/psprd/EMPLOYEE/HRMS/c/ROLE_EMPLOYEE.TL_MSS_EE_SRCH_PRD.GBL');
        await page.waitForSelector("#username");
        await page.type("#username", "alexa818");
        await page.type("#password", "$GoGoldenGophers2020");
        await page.click(".idp3_form-submit");
        await page.waitForSelector("#duo_form");
        console.log("Waiting for Form to load...'");
        const frameHandle = await page.$("#duo_form");
        console.log("Form loaded waiting more...'");
        await page.waitForTimeout(3500);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.waitForTimeout(500);
        console.log("Clicking 'Send Me a Push'");
        await page.keyboard.press("Enter");
        await page.waitForSelector("#lbFrame");
        await page.waitForTimeout(2500);
        console.log("Clicking 'Student Accedemic Support'");
        await page.waitForTimeout(1000);
        //await page.mouse.click(132, 353);
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Enter");

        await page.waitForSelector("#ptifrmtemplate");
        await page.waitForTimeout(2500);

        console.log("Tabbing into input spaces...'");
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);

        await page.keyboard.type("11:00");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.keyboard.type("12:00");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.keyboard.type("12:01");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.keyboard.type("18:00");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Space");
        await page.waitForTimeout(100);
        await page.keyboard.press("ArrowDown");
        await page.waitForTimeout(100);
        await page.keyboard.press("Enter");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");

        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");


        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");

        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");

        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");

        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");  
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Tab");
        await page.waitForTimeout(100);
        await page.keyboard.press("Enter");
        await page.waitForTimeout(4000);
        await page.keyboard.press("Enter");
        request('https://alertzy.app/send?accountKey=m143fegulr79ila&title=ALabs Timesheet Fullfilled!&message=Sir, VAHCS here. I have filled out your timesheet. Have a nice rest of your Wednesday', function (error, response, body) {});
    }catch{
        request('https://alertzy.app/send?accountKey=m143fegulr79ila&title=ALabs Timesheet Filled!&message=Sir, VAHCS here. I tried to fillfull your timesheet and was unsuccessful. I believe I may be malfunctioning', function (error, response, body) {});        
    }
});